dev: template models, initdb, CRUD APIs
FAIMS/FAIMS3 pull request #1144
Opened 2024-09-11 02:14 UTC by PeterBaker0

Implements the CRUD APIs to interact with new template DB. 

Follows the threads around app to initialise the DB, fixes security model issue where members list was empty. 

**Note**: Uses existing `cluster-admin` role for now - we can consider if fine-grained permissions are needed and can add this in using the combination of init methods, security documents, and the API user management (which defines actions against user roles etc). 

Fixes/improves various aspects along the way including using Zod to do runtime validation of payloads, fully typing the templates DB so that PouchDB methods are type safe, replacing default HTML error handler with JSON handler and implementing custom exceptions so that status codes automatically propagate to the error middleware.

2024-09-11 05:22 UTC, stevecassidy requested changes
Main request is for some tests, I'm not able to try this code out without them.

2024-09-11 06:00 UTC, PeterBaker0 commented on library/data-model/src/types.ts
> +
@stevecassidy can we defer doing this - could be a pretty big job and out of scope for this set of features. 

https://jira.csiro.au/browse/BSS-340

2024-09-11 23:13 UTC, stevecassidy commented on library/data-model/src/types.ts
> +
Sure

2024-09-13 02:57 UTC, stevecassidy approved these changes
New changes look good. Really nice work on the tests.  One minor change to remove logging output.

2024-09-13 02:57 UTC, stevecassidy commented on api/src/authkeys/read.ts
>    const signingKey = await KEY_SERVICE.getSigningKey();
Maybe just remove these, a local flag isn't useful.

2024-09-15 23:37 UTC, PeterBaker0 commented
Merging as changes were as discussed, and unit tests are passing.

2024-09-15 23:38 UTC, merged