feat: survey form layout
FAIMS/FAIMS3 pull request #1165
Opened 2024-10-01 06:50 UTC by luke-mcfarlane-rocketlab

## JIRA Ticket

[BSS-382](https://jira.csiro.au/browse/BSS-382)

## Description

Changed the layout of the create site record form to be in a single long view.

## Proposed Changes

- updated form component to show list with headings rather than tabs
- moved errors to the end of the form

## How to Test

This was tested using the Rapid Impact Survey.

1. Navigate to a survey
2. Add a new record
3. Verify layout and form functionality
4. (optional) Open an already created record and verify layout and functionality

## Additional Information

This is an update rather than configurable. Happy to discuss the option of being configurable but it seems currently there are a few bugs in the form code and if we were to maintain both we will need to address these in each version of the component.

## Checklist

- [x] I have confirmed all commits have been signed.
- [x] I have added JSDoc style comments to any new functions or classes.
- [x] Relevant documentation such as READMEs, guides, and class comments are updated.

2024-10-08 22:27 UTC, stevecassidy reviewed
The layout looks ok but we need to have a configuration option to select between this and the old layout.

2024-10-09 00:17 UTC, stevecassidy commented
Thinking about this, the option to use inline vs tabs for sections should be a configuration on the form in the uiSpec.  Then I could if I wanted have one form with tabs and another with inline sections.  Need to add in a configuration option to the Designer.

2024-10-24 22:19 UTC, luke-mcfarlane-rocketlab commented
@stevecassidy issues above have been addressed

2024-10-25 01:02 UTC, stevecassidy requested changes
Generally ok, see my small comments.  We need to document this change to the notebook format but I'll make a separate ticket for that and include the other recent change.

2024-10-28 02:35 UTC, ranisa-gupta16 commented on app/src/gui/components/record/form.tsx
> +                                  bgcolor={'#fafafa'}
Can you use theme specific color variables?

2024-10-29 00:13 UTC, luke-mcfarlane-rocketlab commented
@stevecassidy @ranisa-gupta16 comments actioned

2024-10-30 23:31 UTC, merged