feat: publish record buttons
FAIMS/FAIMS3 pull request #1181
Opened 2024-10-15 05:57 UTC by luke-mcfarlane-rocketlab

## JIRA Ticket

[BSS-389](https://jira.csiro.au/browse/BSS-389)

## Description

Small update to styling, visibility and text of publish record buttons.

## Proposed Changes

- Updated styling, visibility and text of publish record buttons
- Fixed styling issue with form's parent component by removing it

## How to Test

1. Navigate to a survey
2. Add new (or open current) record
3. Scroll down to the buttons at the end of the form

## Additional Information

## Checklist

- [x] I have confirmed all commits have been signed.
- [x] I have added JSDoc style comments to any new functions or classes.
- [x] Relevant documentation such as READMEs, guides, and class comments are updated.

2024-10-17 23:33 UTC, stevecassidy requested changes
The change seems to totally mess up layout on narrower screen widths.  Tried at 1000px wide and the form section shrinks to half the page width. At 590px has switched to narrow view but form is still 2/3 of screen width.

2024-10-30 03:37 UTC, luke-mcfarlane-rocketlab commented
I wasn't able to replicate the issue mentioned above

2024-10-30 22:33 UTC, PeterBaker0 commented
I'll see if I can replicate

2024-10-30 23:44 UTC, PeterBaker0 commented
I can replicate the layout issue e.g. 
![image](https://github.com/user-attachments/assets/b94aaa87-35fb-465d-ae80-93c957e23ad3)

@luke-mcfarlane-rocketlab  to address this and can review after

2024-10-31 00:40 UTC, luke-mcfarlane-rocketlab commented
Ready for re-review @PeterBaker0

2024-10-31 02:23 UTC, PeterBaker0 reviewed
Trusting that you've tested functionality - more important to get things merged at this point. Code looks like mostly styling/minor changes. Am concerned about hardcoding value of Publish button - should it say "Building" for example instead of "record"?

2024-10-31 02:23 UTC, PeterBaker0 commented on app/android/app/src/main/AndroidManifest.xml-e
should this be git ignored?

2024-10-31 02:23 UTC, PeterBaker0 commented on app/src/gui/components/record/formButton.tsx
> +          text="Publish and New Record"
Was this supposed to be informed by the name of the viewset/form e.g. "Site" ?

2024-10-31 04:18 UTC, luke-mcfarlane-rocketlab commented
@PeterBaker0 actioned above

2024-10-31 04:34 UTC, PeterBaker0 approved these changes
Nit pick - but would be better to a) make viewName.split('-').at(0) into a function since it's a bit obtuse why that works b) store it as a constant in component scope rather than derive it twice directly in the text. 

Otherwise once the manifest file is removed lgtm 👍

2024-10-31 04:34 UTC, PeterBaker0 commented on app/android/app/src/main/AndroidManifest.xml-e
@luke-mcfarlane-rocketlab  can you remove this ? It has hardcoded build artifact outputs such as org.fedarch.faims3 etc.

2024-10-31 04:34 UTC, PeterBaker0 commented on app/src/gui/components/record/formButton.tsx
> +          text="Publish and New Record"
@luke-mcfarlane-rocketlab  did you action this?

2024-10-31 04:34 UTC, PeterBaker0 commented on app/android/app/src/main/AndroidManifest.xml-e
can you git remove this sucker?

2024-10-31 05:00 UTC, merged