feat: new conductor :rocket:
FAIMS/FAIMS3 pull request #1257
Opened 2024-12-18 00:43 UTC by luke-mcfarlane-rocketlab

## JIRA Ticket

[<JIRA_TICKET>](https://jira.csiro.com/browse/<JIRA_TICKET>)

## Description

Briefly describe the purpose of this pull request.

## Proposed Changes

List the changes made in this PR.

## How to Test

Explain how to test the changes.

## Additional Information

Add any additional information or context about the pull request here.

## Checklist

- [ ] I have confirmed all commits have been signed.
- [ ] I have added JSDoc style comments to any new functions or classes.
- [ ] Relevant documentation such as READMEs, guides, and class comments are updated.

2025-01-30 01:26 UTC, PeterBaker0 requested changes
Overall it's looking great. 

I think the code is high quality and well structured/documented. 

Some changes to make it ready to merge.

I have left comments on specific aspects, but also noted down some broader concerns. 

- (nice to have) add a clickable cursor on the choose file menu in the new survey form rather than the normal cursor
- (nice to have) highlight the active/current survey/template in the left hand panel and expand if active (e.g. if you go to template -> surveys -> click on the survey, the surveys side bar does not  expand to show that you are there)
- add turbo integration (e.g. build, lint, fix) ensuring proper dependencies for data model etc
- ensure npm is used instead of pnpm for consistency with turbo build and rest of project

**A broader note on auth:**

I'm concerned about the proliferation of auth routes - we probably need to come up with a unified auth strategy which is used by all platforms rather than having special web routes/approaches. This might be okay for now - but I'd like to discuss with the team about having register not require an invite code as is implied by your changes.

2025-01-30 01:26 UTC, PeterBaker0 commented on web/src/auth.tsx
This is nice. 

Can you add the token refresh compatibility? Token refresh has now been merged to main so I think it's high priority to support that. Login gives you access token + refresh token. Refresh token can be exchanged for fresh access token. Access token expires every 5 mins (configurable). I'd recommend setting up a scheduled refresh a minute before the token expires. If you fail to refresh - unauthenticate the user to promote a fresh login.

2025-01-30 01:26 UTC, PeterBaker0 commented on web/src/components/data-table/column-header.tsx
Can you document in the README the file structure - i.e. what goes where and why? Notably distinguishing shadcn components from custom components, routes etc.

2025-01-30 01:26 UTC, PeterBaker0 commented on web/src/components/data-table/data-table.tsx
nice

2025-01-30 01:26 UTC, PeterBaker0 commented on web/src/components/forms/create-survey-from-template-form.tsx
> +      .min(3, {message: 'Survey name must be at least 3 characters.'}),
I think this is 5 actually.

2025-01-30 01:26 UTC, PeterBaker0 commented on web/src/components/logo.tsx
This will need to be configurable as part of theme

2025-01-30 01:26 UTC, PeterBaker0 commented on web/src/components/side-bar/team-switcher.tsx
> + */
I'm guessing this is somewhat boilerplate from shadcn - could you update the nomenclature/docs to reflect our use case - i.e. we don't have a team here right?

2025-01-30 01:26 UTC, PeterBaker0 commented on web/src/components/tables/example.tsx
> +export const columns: ColumnDef<Payment>[] = [
Example component, remove?

2025-01-30 01:26 UTC, PeterBaker0 commented on web/src/components/tables/survey-users.tsx
> +};
Payment?

2025-01-30 01:26 UTC, PeterBaker0 commented on web/src/components/tables/users.tsx
> +};
Payment?

2025-01-30 01:26 UTC, PeterBaker0 commented on web/src/components/theme-provider.tsx
how will this relate with BSS vs Fieldmark themes - what's the plan here - I see system vs dark but that's probably a different theme than a build time env variable switch like we have with the main app

2025-01-30 01:26 UTC, PeterBaker0 commented on web/src/components/ui/alert.tsx
this is shadcn isn't it? I'll ignore all these /ui components. E.g. what the hell is cva? haha

2025-01-30 01:26 UTC, PeterBaker0 commented on web/src/hooks/use-mobile.tsx
cool

2025-01-30 01:26 UTC, PeterBaker0 commented on web/src/index.css
Could you add a class comment here explaining when/why someone should edit these?

2025-01-30 01:26 UTC, PeterBaker0 commented on web/src/lib/queries.ts
Can you ensure that the response model is typed in this client - i.e. type generics for the get method or whatever which types the response model. I don't want to have to type cast the useQuery results anywhere I use it.

2025-01-30 01:26 UTC, PeterBaker0 commented on web/src/routes/_auth/surveys/$surveyId.tsx
Could you add some text to the README explaining how/where a developer should add new routes - and basic principles of how to do this with Tanstack router - okay if you just link to their docs for main steps.

2025-01-30 01:26 UTC, PeterBaker0 commented on web/src/routes/_auth/templates/$templateId.tsx
One pattern I've found very user friendly is having the tab as a query string argument which is automatically tracked so that deep links go straight to the tab - is this something tanstack router can do? Otherwise I just added a very nice custom hook in the main FAIMS3 code base we could reuse which provides a nice typed query string interface.

2025-01-30 01:26 UTC, PeterBaker0 commented on web/src/routes/_auth/users.tsx
Overall the routes file structure is a little confusing to me - so its routes/_auth/<all protected routes>

At first glance, you would expect that _auth/ would contain only auth related routes like login/register etc - rather than all the protected routes in the app - is there a way to separate these things so you could have like /_auth and also /templates /notebooks? 

Not urgent but I find the structure a bit unintuitive at first glance.

2025-01-30 02:19 UTC, stevecassidy reviewed
Generally good and just what we need but some language problems with excessive use of 'survey' that needs to be 'project' and needs a customisation option as per the app configuration.  In general borrow as much configuration from the app as possible.  

Login needs to redirect to the API auth endpoint to get other configured login options.  

Haven't looked deeply yet but looks very neat and just what we need.

2025-01-30 02:19 UTC, stevecassidy commented on web/src/auth.tsx
> +
We need to support the full range of login options that the backend supports.  It can be configured to support Google login etc.  Best option might be to redirect to the API login page for actual login entry as the app does, then you don't need to duplicate here.

2025-01-30 02:19 UTC, stevecassidy commented on web/src/auth.tsx
> +    const response = await fetch('http://localhost:8080/web/login/local', {
This needs to use the configured API URL but see my other comment about not doing it this way.

2025-01-30 02:19 UTC, stevecassidy commented on web/src/components/tabs/survey/survey-actions.tsx
> +import {Alert, AlertTitle, AlertDescription} from '@/components/ui/alert';
You've used 'survey' to name these modules! Try the neutral 'project' as per the app sourcecode.

2025-01-30 02:19 UTC, stevecassidy commented on web/src/components/tabs/survey/survey-users.tsx
> +        `http://localhost:8080/api/notebooks/${surveyId}/users`,
Hard coded API endpoint

2025-01-30 02:19 UTC, stevecassidy commented on web/src/components/tables/survey-users.tsx
> +    accessorKey: 'email',
Email is not showing in my deployment.

2025-01-30 02:23 UTC, stevecassidy commented on api/src/api/auth.ts
> +  );
These aren't needed since we should be doing login from the one page served by the API and getting the token on redirect back to the front end.

2025-01-30 02:24 UTC, luke-mcfarlane-rocketlab commented on web/src/routes/_auth/users.tsx
_route folders add the layout and apply the functions in the _route.tsx file but do not add to the URL (rather than being used for organising pages). E.g. in this instance, for any page in "_auth/" the _auth.tsx has a before load that checks if the user is authenticated and adds the sidebar.

You are able to add what is called "route groups" to organise pages using (group) syntax but I find it confusing when using file based routing if there are folders without function.

The intuition for the name was that anything within _auth/ would require authentication but happy to change this if you can think of a more intuitive name.

2025-01-30 02:25 UTC, luke-mcfarlane-rocketlab commented on web/src/routes/_auth/templates/$templateId.tsx
Definitely agree with the pattern and is something that tanstack router supports. The current behaviour was the default for shadcn tabs and so I left it as I did not think this would be a priority.

2025-01-30 02:26 UTC, stevecassidy commented on web/index.html
> +    <title>Fieldmark Manager</title>
System name can come from /api/info on the server.   Retain Conductor unless we can come up with a better name (I'm not wedded to it).

2025-01-30 03:18 UTC, luke-mcfarlane-rocketlab commented on api/src/api/auth.ts
> +}
Good shout - I forgot about this one

2025-01-30 05:40 UTC, luke-mcfarlane-rocketlab commented on api/src/api/auth.ts
> +  });
Agree, we can lump this in with the broader auth discussion.

2025-01-30 05:42 UTC, luke-mcfarlane-rocketlab commented on api/src/api/auth.ts
> +  );
Happy to use either approach but might be worth a discussion as this approach removed the need for the user to navigate between platforms to log in.

2025-01-30 06:04 UTC, stevecassidy commented on api/src/api/auth.ts
> +  );
No need to navigate between platforms, API just provides the login page that we redirect to from here, then redirects back. Same way as the app.   Seamless for the user.

2025-02-04 06:00 UTC, luke-mcfarlane-rocketlab commented on web/src/components/ui/alert.tsx
Yeh thats right, you can ignore all the shadcn components in `ui/`. `cva` just provides a way to make typesafe tailwind classes with variants. If you look at the alertVariants function it is just taking the variant and returning the corresponding classNames as well as some classnames for all variants. Happy to go over any of the shadcn components, for the most part they are just divs/radix components with tailwind classes

2025-02-04 06:05 UTC, luke-mcfarlane-rocketlab commented on web/src/index.css
Will also include in the README as this is how one would update the colour's of the application.

2025-02-05 00:51 UTC, luke-mcfarlane-rocketlab commented on web/src/auth.tsx
This might take some more thought and time around design and implementation - will create a ticket and push in separate PR

2025-02-05 02:53 UTC, luke-mcfarlane-rocketlab commented on web/src/components/logo.tsx
Will add a separate ticket/PR for this one

2025-02-05 02:54 UTC, luke-mcfarlane-rocketlab commented on web/src/components/theme-provider.tsx
This is mainly a theme setup script - the actual colours can be modified in the `src/index.css` which will differ between the two deployments.

2025-02-05 02:58 UTC, luke-mcfarlane-rocketlab commented on web/src/routes/_auth/templates/$templateId.tsx
I can add this as a low prio ticket.

2025-02-05 05:30 UTC, luke-mcfarlane-rocketlab commented on web/src/auth.tsx
> +
Removed the auth endpoints in this PR

2025-02-05 05:30 UTC, luke-mcfarlane-rocketlab commented on web/src/auth.tsx
> +    const response = await fetch('http://localhost:8080/web/login/local', {
Removed the auth endpoints in this PR

2025-02-09 23:26 UTC, PeterBaker0 approved these changes
Pending couple of minor comments, lgtm 🚀

2025-02-09 23:26 UTC, PeterBaker0 commented on web/src/components/forms/create-project-from-template.tsx
> +    const response = await fetch('http://localhost:8080/api/notebooks', {
localhost!

2025-02-09 23:26 UTC, PeterBaker0 commented on web/src/components/forms/create-project-from-template.tsx
> +      message: `${NOTEBOOK_NAME_CAPITALIZED} name must be at least 3 characters.`,
5 characters*

2025-02-09 23:26 UTC, PeterBaker0 commented on web/src/context/auth-provider.tsx
> +   * Logs in the user with a token and refresh token.
This is kind of a weird phrasing of this - you are not logging in the user right? You are just retrieving fresh user details based on the token (which implies the user was already logged in?)

2025-02-09 23:26 UTC, PeterBaker0 commented on web/src/context/auth-provider.tsx
> +    }
Some issues here I think 

a) only try and refresh the token if the current access token is expiring soon (e.g. <1 minute) (saves network traffic)
b) if the refresh fails, don't immediately boot the user out, instead prompt a refresh of the isAuthenticated state based on the existing access token - if it's not expired yet (or within some margin) then let the user continue working and try the refresh again on the next interval

2025-02-09 23:26 UTC, PeterBaker0 commented on web/src/context/auth-provider.tsx
> +      const intervalId = setInterval(refreshToken, 5 * 60 * 1000);
These intervals are configurable in the /app - can you use the same env variable/build config approach for conductor see VITE_REFRESH_TOKEN_INTERVAL etc

2025-02-09 23:39 UTC, stevecassidy commented on web/src/routes/users.tsx
> +      data={data?.map((user: any) => ({...user, email: user.emails[0]}))}
Getting a crash here for an unprivileged user, 'data?.map is not a function'.  Also, 'user' here is shadowing 'user' from useAuth().

2025-02-09 23:43 UTC, stevecassidy commented on web/src/routes/index.tsx
> +  return <Card>Home</Card>;
Home should have some content. I created a new home page for old Conductor with links to the web app etc.  Also need to have an option to copy a user token for scripts somewhere - currently on the old conductor home page - that could be in the user profile.

2025-02-10 00:11 UTC, stevecassidy reviewed
Looking good! See comments about package versions but happy to merge once that is dealt with.

2025-02-10 00:11 UTC, stevecassidy commented on web/src/routes/profile.tsx
> +
Not sure we need both 'Account' and 'Profile' but you could usefully list the global roles that the user has here (cluster-admin, notebook-creator).  Maybe also what auth method they have used (local password, google).

2025-02-12 05:09 UTC, merged